services:
  # -----------------------------------------------
  # CONTENEDOR 1: LA BASE DE DATOS (PostgreSQL)
  # -----------------------------------------------
  base-de-datos:
    image: postgres:15
    environment:
      POSTGRES_DB: poli_db
      POSTGRES_USER: usuario_poli
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"

  # -----------------------------------------------
  # CONTENEDOR 2: EL BACKEND (Django)
  # -----------------------------------------------
  backend-app:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8080:8000"
    depends_on:
      - base-de-datos

  # -----------------------------------------------
  # CONTENEDOR 3: JENKINS (Integración Continua)
  # -----------------------------------------------
  jenkins:
    image: jenkins/jenkins:lts
    user: root # Evita problemas de permisos locales
    ports:
      - "8081:8080"   # Tu PC usa el 8081, Jenkins internamente usa el 8080
      - "50000:50000" # Puerto estándar para comunicación de agentes Jenkins
    volumes:
      - jenkins_data:/var/jenkins_home

# Declaración de volúmenes persistentes
volumes:
  jenkins_data: